import 'server-only'

import {
  disqualify,
  GATE_CHECK_NAMES,
  type GateName,
  runGates,
  sellCase,
  type CandidateInput,
  type Disqualifier,
  type GateResult,
  type SellReason,
} from './edge-gates'
import { projectPoints } from './edge-projection'
import {
  fixtureScore,
  fixturesFor,
  horizonGameweeks,
  type FixtureIndex,
} from './fixtures'
import type { Horizon } from './horizon'
import type { SquadPlayer } from './squad'
import type { FplBootstrap, FplElement } from './types'

/**
 * The Edge (section 7.9): complete transfer packages, not two rankings.
 *
 * ## Buys are paired to sells, always
 *
 * Budget binds them together. A buy list generated independently of a sell
 * list produces suggestions the reader cannot fund, which is the failure the
 * GW4 log kept running into: "You have £0.0m in the bank, which is exactly why
 * Palmer and Rogers are locked out." Every move here is a pair, and every pair
 * is checked against funds that include the proceeds of its own sale.
 *
 * ## Packages vary on one axis at a time
 *
 * Two to four packages, generated by moving a single dial so the difference
 * between them is explicable rather than arbitrary: spend every transfer
 * versus bank one, and safest versus highest ceiling. Where two candidates are
 * close they become alternatives *inside* one package rather than a package of
 * their own, which is how the log presents them: "Higher-ceiling alternative:
 * De Cuyper instead of Hall."
 */

/** Section 7.9: never more than four, never fewer than two when moves exist. */
const MAX_PACKAGES = 4

/** Projected points within this of the best are alternatives, not packages. */
const ALTERNATIVE_MARGIN = 1.5

/** How many rejections to show. Enough to be evidence, few enough to read. */
const MAX_REJECTIONS = 5

/**
 * At most this many of them are fixture clashes.
 *
 * Clashes are the most interesting rejection and the least reproducible, so
 * they lead — but a list of five clashes says nothing about the tests, and the
 * reader learns more from seeing both kinds of reason than from five of the
 * rarer one.
 */
const MAX_CONFLICT_REJECTIONS = 2

export type Move = {
  out: EdgePlayer
  in: EdgePlayer
  gates: GateResult
  /** Cash freed (positive) or spent (negative) by this pair, in tenths. */
  cashDelta: number
  /** A close second for the same slot, when one exists. */
  alternative: EdgePlayer | null
  alternativeNote: string | null
}

export type EdgePlayer = {
  id: number
  name: string
  club: string
  clubShort: string
  teamId: number
  position: string
  /** In tenths (constraint 4). */
  price: number
  projected: number
  fixtureScore: number
  form: number
  ownership: number
  netTransfers: number
  /** Clubs in the squad this player faces inside the horizon (section 7.9). */
  conflicts: string[]
}

export type EdgePackage = {
  id: string
  title: string
  moves: Move[]
  /** Money left after the whole package, in tenths. */
  moneyLeft: number
  /** Transfers deliberately not spent. */
  banked: number
  /** One line on what it gains. */
  gains: string
  /** One line on what it costs. */
  costs: string
  /** Total projected gain over the horizon, across every move. */
  pointsGain: number
}

export type Rejection = {
  name: string
  price: number
  reason: string
}

export type EdgeResult = {
  packages: EdgePackage[]
  /** Squad players the sell gate flagged. Often none, which is a real answer. */
  sells: { player: EdgePlayer; reasons: SellReason[] }[]
  rejections: Rejection[]
  /** True when every package ends on the same fifteen. */
  convergent: boolean
  bank: number
  transfers: number
}

export function buildEdge({
  bootstrap,
  fixtures,
  squad,
  startGameweek,
  horizon,
  longHorizon,
  matchesPlayed,
  ownershipOf,
  bank,
  transfers,
}: {
  bootstrap: FplBootstrap
  fixtures: FixtureIndex
  squad: SquadPlayer[]
  startGameweek: number
  horizon: Horizon
  longHorizon: number
  matchesPlayed: Map<number, number>
  ownershipOf: (playerId: number) => number
  /** In tenths. */
  bank: number
  transfers: number
}): EdgeResult {
  const gameweeks = horizonGameweeks(startGameweek, horizon)
  const positionOf = new Map(
    bootstrap.element_types.map((type) => [type.id, type.singular_name_short])
  )
  const clubOf = new Map(bootstrap.teams.map((team) => [team.id, team]))
  const owned = new Set(squad.map((player) => player.id))
  const squadTeamIds = new Set(squad.map((player) => player.teamId))

  const clubCounts = new Map<number, number>()
  for (const player of squad) {
    clubCounts.set(player.teamId, (clubCounts.get(player.teamId) ?? 0) + 1)
  }

  const project = (element: FplElement, weeks: number[]) =>
    projectPoints(
      {
        position: positionOf.get(element.element_type) ?? '?',
        minutes: element.minutes,
        matchesPlayed: matchesPlayed.get(element.team) ?? 0,
        status: element.status,
        chanceOfPlayingNextRound: element.chance_of_playing_next_round,
        expectedGoalInvolvementsPer90: perNinety(
          element.expected_goal_involvements,
          element.minutes
        ),
        defensiveContributionPer90: element.defensive_contribution_per_90,
      },
      weeks.flatMap((gameweek) => fixturesFor(fixtures, element.team, gameweek))
    ).points

  const longWeeks = horizonGameweeks(startGameweek, longHorizon as Horizon)

  const candidates: CandidateInput[] = bootstrap.elements.map((element) => ({
    element,
    projected: project(element, gameweeks),
    projectedLong: project(element, longWeeks),
    minutesPerMatch: minutesRate(element, matchesPlayed.get(element.team) ?? 0),
    longHorizonPercentile: 0,
  }))

  // Test 3 is a ranking question, so the percentile is computed once across
  // each position rather than per pairing. Comparing a defender's long-horizon
  // projection against forwards would measure position, not quality.
  fillPercentiles(candidates, positionOf)

  const byId = new Map(candidates.map((c) => [c.element.id, c]))

  // What ordinary form looks like for each position, among players actually
  // getting minutes. The sell gate measures against this rather than a fixed
  // number, so a goalkeeper is judged against goalkeepers.
  const medianForm = positionMedianForm(candidates, positionOf)

  const toPlayer = (candidate: CandidateInput): EdgePlayer => {
    const { element } = candidate
    const club = clubOf.get(element.team)
    return {
      id: element.id,
      name: element.web_name,
      club: club?.name ?? '',
      clubShort: club?.short_name ?? '',
      teamId: element.team,
      position: positionOf.get(element.element_type) ?? '?',
      price: element.now_cost,
      projected: candidate.projected,
      fixtureScore: fixtureScore(fixtures, element.team, startGameweek, horizon)
        .score,
      form: Number(element.form) || 0,
      ownership: ownershipOf(element.id),
      netTransfers: element.transfers_in_event - element.transfers_out_event,
      conflicts: conflictsWith(
        element.team,
        squadTeamIds,
        fixtures,
        // The gameweek this transfer is *for*, not the whole horizon. Over
        // five gameweeks almost every player meets some club in the squad, so
        // a wide window turns a real signal into noise — and the log's own
        // example is specific: De Cuyper "plays at Coventry in GW4".
        gameweeks.slice(0, 1),
        clubOf
      ),
    }
  }

  // --- The sell gate -----------------------------------------------------

  const sells = squad
    .map((player) => {
      const candidate = byId.get(player.id)
      if (!candidate) {
        return null
      }
      const score = fixtureScore(
        fixtures,
        player.teamId,
        startGameweek,
        horizon
      ).score
      const verdict = sellCase(
        candidate.element,
        score,
        candidate.minutesPerMatch,
        medianForm.get(player.position) ?? 0
      )
      return verdict.flagged
        ? { player: toPlayer(candidate), reasons: verdict.reasons }
        : null
    })
    .filter((entry) => entry !== null)

  if (sells.length === 0) {
    return {
      packages: [],
      sells: [],
      rejections: [],
      convergent: false,
      bank,
      transfers,
    }
  }

  // --- Pair every flagged sell with every legal buy -----------------------

  // Two lists, because they are not equally interesting. A player who failed a
  // test failed arithmetic anyone could repeat; a player who passed every test
  // and was still cut for a fixture clash is the one piece of reasoning the
  // reader could not have reached from the other four views. Conflicts are
  // emitted first so they survive the cut to five.
  const conflictRejections: Rejection[] = []
  const gateRejections: Rejection[] = []
  const rejected = new Set<number>()

  const noteRejection = (
    element: FplElement,
    reason: string,
    into: Rejection[]
  ) => {
    if (rejected.has(element.id) || into.length >= MAX_REJECTIONS) {
      return
    }
    rejected.add(element.id)
    into.push({ name: element.web_name, price: element.now_cost, reason })
  }

  const optionsFor = (sellEntry: (typeof sells)[number]) => {
    const sellCandidate = byId.get(sellEntry.player.id)
    if (!sellCandidate) {
      return []
    }
    const sellPrice = sellEntry.player.price

    return candidates
      .filter(
        (c) =>
          positionOf.get(c.element.element_type) === sellEntry.player.position
      )
      .map((candidate) => {
        const blocked = disqualify(candidate, {
          owned,
          clubCounts,
          sellingTeamId: sellEntry.player.teamId,
          fundsAvailable: bank,
          sellPrice,
        })
        if (blocked) {
          return { candidate, blocked, gates: null }
        }
        const gates = runGates(candidate, sellCandidate, gameweeks.length)
        return { candidate, blocked: null as Disqualifier | null, gates }
      })
      .filter((option) => {
        if (option.blocked) {
          return false
        }
        if (!option.gates?.qualifies) {
          // The reason has to be the thing that actually cut them. Reporting a
          // fixture clash for a player who failed the floor test would be
          // telling the reader something true about a decision it did not make.
          if (option.gates) {
            noteRejection(
              option.candidate.element,
              `Fails ${option.gates.failed.map(gateReason).join(' and ')}`,
              gateRejections
            )
          }
          return false
        }

        return true
      })
      .map((option) => ({
        player: toPlayer(option.candidate),
        gates: option.gates as GateResult,
        projectedLong: option.candidate.projectedLong,
      }))
      .sort((a, b) => b.player.projected - a.player.projected)
  }

  const slots = sells
    .map((sell) => ({ sell, options: optionsFor(sell) }))
    .filter((slot) => slot.options.length > 0)

  if (slots.length === 0) {
    return {
      packages: [],
      sells,
      rejections: mixRejections(conflictRejections, gateRejections),
      convergent: false,
      bank,
      transfers,
    }
  }

  // --- Assemble packages --------------------------------------------------

  const spend = Math.min(transfers, slots.length)

  const build = (
    label: string,
    title: string,
    take: number,
    pick: (options: Option[]) => number
  ): EdgePackage | null => {
    let funds = bank
    const moves: Move[] = []

    // Slots are taken in order of how badly the sell needs replacing, and each
    // purchase is checked against funds that already include this sale. That
    // is what makes the whole package affordable end to end rather than each
    // move affordable on its own.
    for (const slot of slots.slice(0, take)) {
      const affordable = slot.options.filter(
        (option) => option.player.price <= funds + slot.sell.player.price
      )
      if (affordable.length === 0) {
        continue
      }
      const chosen =
        affordable[Math.min(pick(affordable), affordable.length - 1)]
      const alternative = affordable.find(
        (option) =>
          option.player.id !== chosen.player.id &&
          Math.abs(option.player.projected - chosen.player.projected) <=
            ALTERNATIVE_MARGIN
      )

      funds += slot.sell.player.price - chosen.player.price
      moves.push({
        out: slot.sell.player,
        in: chosen.player,
        gates: chosen.gates,
        cashDelta: slot.sell.player.price - chosen.player.price,
        alternative: alternative?.player ?? null,
        alternativeNote: alternative
          ? describeAlternative(chosen.player, alternative.player)
          : null,
      })
    }

    if (moves.length === 0) {
      return null
    }

    const pointsGain = moves.reduce(
      (total, move) => total + (move.in.projected - move.out.projected),
      0
    )

    return {
      id: label,
      title,
      moves,
      moneyLeft: funds,
      banked: transfers - moves.length,
      pointsGain,
      gains: describeGains(moves, pointsGain),
      costs: describeCosts(
        moves,
        funds,
        transfers - moves.length,
        slots.slice(take).map((slot) => slot.sell.player)
      ),
    }
  }

  // Written out, not numeric: these are prose headings, and "2 transfers,
  // safest" reads as a fragment where "Two transfers, safest" reads as a name.
  const moves = (n: number) =>
    `${titleCaseNumber(n)} transfer${n === 1 ? '' : 's'}`
  const packages = [
    build('all-safest', `${moves(spend)}, safest`, spend, safest),
    build(
      'all-ceiling',
      `${moves(spend)}, biggest upside`,
      spend,
      highestCeiling
    ),
    spend > 1
      ? build(
          'bank-one',
          `${moves(spend - 1)}, bank the rest`,
          spend - 1,
          safest
        )
      : null,
  ].filter((entry) => entry !== null)

  // Two packages that make identical moves are one package described twice.
  const unique: EdgePackage[] = []
  for (const candidate of packages) {
    const key = signature(candidate)
    if (!unique.some((existing) => signature(existing) === key)) {
      unique.push(candidate)
    }
  }

  const ranked = unique
    .sort((a, b) => b.pointsGain - a.pointsGain)
    .slice(0, MAX_PACKAGES)

  // A candidate that cleared every test and still did not make a package is
  // the rejection most worth showing, because the reason is never visible
  // anywhere else in the app.
  const used = new Set(
    ranked.flatMap((pack) => pack.moves.map((move) => move.in.id))
  )
  for (const slot of slots) {
    for (const option of slot.options) {
      if (used.has(option.player.id) || option.player.conflicts.length === 0) {
        continue
      }
      noteRejection(
        candidates.find((c) => c.element.id === option.player.id)!.element,
        `Passes the tests, but plays ${option.player.conflicts.join(' and ')} in GW${gameweeks[0]}, where you already own players`,
        conflictRejections
      )
    }
  }

  return {
    packages: ranked,
    sells,
    rejections: mixRejections(conflictRejections, gateRejections),
    convergent: ranked.length > 1 && sameDestination(ranked),
    bank,
    transfers,
  }
}

/**
 * The two package axes, as index pickers over the same option list.
 *
 * They have to disagree or the packages are duplicates. **Safest** takes the
 * best projection over the horizon actually selected, breaking ties towards
 * the more owned player: a template pick fails in company, which is the whole
 * point of safe. **Highest ceiling** takes the best long-horizon projection,
 * breaking ties towards the *less* owned player, because upside against your
 * rivals is what a ceiling means.
 *
 * Ranking on form, which this did first, produced a "ceiling" package worth
 * 1.9 points against the safe package's 10.9 — not a bolder version of the
 * same idea, just a worse one.
 */
type Option = {
  player: EdgePlayer
  gates: GateResult
  projectedLong: number
}

/**
 * A fixture against a club you own is a cost, not a veto.
 *
 * Rejecting on it outright cut De Cuyper — who the GW4 log went on to pick,
 * having decided the clash was "softer than I made it sound: in a 0-0 both
 * bank a clean sheet". The two only pull against each other on the attacking
 * side. So a clash costs a candidate a fraction of a projected point per club
 * involved, which reorders near-ties without ever overturning a real gap.
 */
const CONFLICT_PENALTY = 0.75

const adjusted = (option: Option): number =>
  option.player.projected - CONFLICT_PENALTY * option.player.conflicts.length

function safest(options: Option[]): number {
  let best = 0
  for (let i = 1; i < options.length; i++) {
    const a = options[i]
    const b = options[best]
    if (
      adjusted(a) > adjusted(b) ||
      (adjusted(a) === adjusted(b) && a.player.ownership > b.player.ownership)
    ) {
      best = i
    }
  }
  return best
}

function highestCeiling(options: Option[]): number {
  let best = 0
  for (let i = 1; i < options.length; i++) {
    const a = options[i]
    const b = options[best]
    if (
      a.projectedLong > b.projectedLong ||
      (a.projectedLong === b.projectedLong &&
        a.player.ownership < b.player.ownership)
    ) {
      best = i
    }
  }
  return best
}

/**
 * Clubs in the squad this player faces inside the horizon.
 *
 * Section 7.9: the GW4 log rejected De Cuyper partly because he plays at
 * Coventry while the reader owns three Coventry assets. Nothing else in the
 * app surfaces that, and it is only computable by crossing the squad against
 * the fixture list.
 */
function conflictsWith(
  teamId: number,
  squadTeamIds: Set<number>,
  fixtures: FixtureIndex,
  gameweeks: number[],
  clubOf: Map<number, { short_name: string }>
): string[] {
  const clashes = new Set<string>()
  for (const gameweek of gameweeks) {
    for (const fixture of fixturesFor(fixtures, teamId, gameweek)) {
      const opponentId = [...clubOf.keys()].find(
        (id) => clubOf.get(id)?.short_name === fixture.opponent
      )
      if (opponentId !== undefined && squadTeamIds.has(opponentId)) {
        clashes.add(fixture.opponent)
      }
    }
  }
  return [...clashes]
}

function describeAlternative(chosen: EdgePlayer, other: EdgePlayer): string {
  if (other.price > chosen.price) {
    return `${other.name} is £${((other.price - chosen.price) / 10).toFixed(1)}m more for a similar projection`
  }
  if (other.form > chosen.form) {
    return `${other.name} is in better form on a similar projection`
  }
  return `${other.name} projects within a point and is ${other.ownership < chosen.ownership ? 'less' : 'more'} owned`
}

function describeGains(moves: Move[], pointsGain: number): string {
  const best = [...moves].sort(
    (a, b) =>
      b.in.projected - b.out.projected - (a.in.projected - a.out.projected)
  )[0]
  return `About ${pointsGain.toFixed(1)} projected points over the horizon, led by ${best.out.name} to ${best.in.name}.`
}

function describeCosts(
  moves: Move[],
  moneyLeft: number,
  banked: number,
  unsold: EdgePlayer[]
): string {
  const money = `Leaves £${(moneyLeft / 10).toFixed(1)}m`

  // Not spending a transfer means keeping a player the sell gate flagged, and
  // that is what separates this package from the one that spends them all.
  if (unsold.length > 0) {
    return `Holds ${unsold.map((p) => p.name).join(' and ')} another week, still falling. ${money}.`
  }
  const conflicts = moves.filter((move) => move.in.conflicts.length > 0)
  if (conflicts.length > 0) {
    return `${conflicts[0].in.name} faces ${conflicts[0].in.conflicts.join(' and ')} in the first gameweek, where you already own players. ${money}.`
  }
  if (banked === 0) {
    return `${money} and no transfer in hand for late team news.`
  }
  return `${money}, with ${banked} transfer${banked === 1 ? '' : 's'} still in hand.`
}

/**
 * Clashes first, capped, then test failures fill the rest.
 *
 * Both kinds earn their place: the clash is reasoning nothing else in the app
 * could produce, the test failure shows the gate actually rejecting people.
 */
function mixRejections(
  conflicts: Rejection[],
  gates: Rejection[]
): Rejection[] {
  const leading = conflicts.slice(0, MAX_CONFLICT_REJECTIONS)
  return [...leading, ...gates].slice(0, MAX_REJECTIONS)
}

/** One shared source for the check names, so badge and rejection agree. */
function gateReason(gate: GateName): string {
  return GATE_CHECK_NAMES[gate]
}

/** Small numbers read as words in a heading; beyond ten, digits are clearer. */
export function spellNumber(value: number): string {
  const words = [
    'Zero',
    'One',
    'Two',
    'Three',
    'Four',
    'Five',
    'Six',
    'Seven',
    'Eight',
    'Nine',
    'Ten',
  ]
  return words[value] ?? String(value)
}

function titleCaseNumber(value: number): string {
  return spellNumber(value)
}

function signature(pack: EdgePackage): string {
  return pack.moves
    .map((move) => `${move.out.id}>${move.in.id}`)
    .sort()
    .join('|')
}

/** Do these packages end on the same fifteen, by a different route? */
function sameDestination(packages: EdgePackage[]): boolean {
  const destination = (pack: EdgePackage) =>
    [...pack.moves.map((move) => move.in.id)].sort().join(',')
  const first = destination(packages[0])
  return packages.every((pack) => destination(pack) === first)
}

/**
 * Where each player sits among their own position on the long horizon.
 *
 * Mutates in place: the array is built once and every candidate needs its
 * percentile before any pairing runs, so a second pass is cheaper than
 * threading a lookup through.
 */
function fillPercentiles(
  candidates: CandidateInput[],
  positionOf: Map<number, string>
): void {
  const groups = new Map<string, CandidateInput[]>()
  for (const candidate of candidates) {
    const position = positionOf.get(candidate.element.element_type) ?? '?'
    const group = groups.get(position)
    if (group) {
      group.push(candidate)
    } else {
      groups.set(position, [candidate])
    }
  }

  for (const group of groups.values()) {
    const sorted = [...group].sort((a, b) => a.projectedLong - b.projectedLong)
    sorted.forEach((candidate, index) => {
      candidate.longHorizonPercentile =
        sorted.length <= 1 ? 1 : index / (sorted.length - 1)
    })
  }
}

/**
 * Median form per position, over players getting regular minutes.
 *
 * Recomputed every request from the same population, so it moves with the
 * season instead of being a number written down in August.
 */
function positionMedianForm(
  candidates: CandidateInput[],
  positionOf: Map<number, string>
): Map<string, number> {
  const groups = new Map<string, number[]>()
  for (const candidate of candidates) {
    if (candidate.minutesPerMatch < 60) {
      continue
    }
    const position = positionOf.get(candidate.element.element_type) ?? '?'
    const form = Number(candidate.element.form) || 0
    const group = groups.get(position)
    if (group) {
      group.push(form)
    } else {
      groups.set(position, [form])
    }
  }

  const medians = new Map<string, number>()
  for (const [position, forms] of groups) {
    forms.sort((a, b) => a - b)
    medians.set(position, forms[Math.floor((forms.length - 1) / 2)])
  }
  return medians
}

function perNinety(total: string | number, minutes: number): number {
  const value = typeof total === 'number' ? total : Number(total)
  if (!Number.isFinite(value) || minutes <= 0) {
    return 0
  }
  return (value / minutes) * 90
}

function minutesRate(element: FplElement, matchesPlayed: number): number {
  return matchesPlayed <= 0 ? 0 : element.minutes / matchesPlayed
}

// ---------------------------------------------------------------------------
// Best picks by position
// ---------------------------------------------------------------------------

/** How many to show per position. A goalkeeper choice is narrower than the rest. */
const PICKS_PER_POSITION: Record<string, number> = {
  GKP: 3,
  DEF: 5,
  MID: 5,
  FWD: 5,
}

export type PositionPicks = {
  position: string
  players: PickRow[]
}

export type PickRow = EdgePlayer & {
  /** One line on what this player would bring. */
  benefit: string
  /** Ownership across all FPL managers, for contrast with the scope figure. */
  globalOwnership: number
}

/**
 * The best available player in each position over the horizon, ignoring money.
 *
 * Deliberately **price agnostic**: this is a shortlist of who is worth having,
 * not a list of who can be afforded today. The packages above already answer
 * the affordability question, and answering it twice would hide the target a
 * reader might sell two players to reach.
 *
 * Only players not already owned, because a suggestion to buy someone in the
 * squad is not a suggestion. Availability, minutes and the obscurity rule
 * still apply — an injured or fringe player is not a pick at any price.
 */
export function buildPositionPicks({
  bootstrap,
  fixtures,
  squad,
  startGameweek,
  horizon,
  longHorizon,
  matchesPlayed,
  ownershipOf,
}: {
  bootstrap: FplBootstrap
  fixtures: FixtureIndex
  squad: SquadPlayer[]
  startGameweek: number
  horizon: Horizon
  longHorizon: number
  matchesPlayed: Map<number, number>
  ownershipOf: (playerId: number) => number
}): PositionPicks[] {
  const gameweeks = horizonGameweeks(startGameweek, horizon)
  const longWeeks = horizonGameweeks(startGameweek, longHorizon as Horizon)
  const positionOf = new Map(
    bootstrap.element_types.map((type) => [type.id, type.singular_name_short])
  )
  const clubOf = new Map(bootstrap.teams.map((team) => [team.id, team]))
  const owned = new Set(squad.map((player) => player.id))
  const squadTeamIds = new Set(squad.map((player) => player.teamId))

  const project = (element: FplElement, weeks: number[]) =>
    projectPoints(
      {
        position: positionOf.get(element.element_type) ?? '?',
        minutes: element.minutes,
        matchesPlayed: matchesPlayed.get(element.team) ?? 0,
        status: element.status,
        chanceOfPlayingNextRound: element.chance_of_playing_next_round,
        expectedGoalInvolvementsPer90: perNinety(
          element.expected_goal_involvements,
          element.minutes
        ),
        defensiveContributionPer90: element.defensive_contribution_per_90,
      },
      weeks.flatMap((gameweek) => fixturesFor(fixtures, element.team, gameweek))
    ).points

  const candidates = bootstrap.elements
    .filter((element) => !owned.has(element.id))
    .map((element) => ({
      element,
      position: positionOf.get(element.element_type) ?? '?',
      projected: project(element, gameweeks),
      projectedLong: project(element, longWeeks),
      minutesPerMatch: minutesRate(
        element,
        matchesPlayed.get(element.team) ?? 0
      ),
      longHorizonPercentile: 0,
    }))

  fillPercentiles(candidates, positionOf)

  const eligible = candidates.filter((candidate) => {
    const blocked = disqualify(candidate, {
      owned,
      clubCounts: new Map(),
      sellingTeamId: null,
      // Price agnostic: the money checks are handed an unreachable budget so
      // the availability, minutes and obscurity rules still run and the
      // affordability one cannot fire.
      fundsAvailable: Number.MAX_SAFE_INTEGER,
      sellPrice: 0,
    })
    return blocked === null
  })

  return Object.entries(PICKS_PER_POSITION).map(([position, count]) => ({
    position,
    players: eligible
      .filter((candidate) => candidate.position === position)
      .sort((a, b) => b.projected - a.projected)
      .slice(0, count)
      .map((candidate) => {
        const { element } = candidate
        const club = clubOf.get(element.team)
        const score = fixtureScore(
          fixtures,
          element.team,
          startGameweek,
          horizon
        ).score
        const row: PickRow = {
          id: element.id,
          name: element.web_name,
          club: club?.name ?? '',
          clubShort: club?.short_name ?? '',
          teamId: element.team,
          position: candidate.position,
          price: element.now_cost,
          projected: candidate.projected,
          fixtureScore: score,
          form: Number(element.form) || 0,
          ownership: ownershipOf(element.id),
          globalOwnership: Number(element.selected_by_percent) || 0,
          netTransfers:
            element.transfers_in_event - element.transfers_out_event,
          conflicts: conflictsWith(
            element.team,
            squadTeamIds,
            fixtures,
            gameweeks.slice(0, 1),
            clubOf
          ),
          benefit: '',
        }
        row.benefit = describeBenefit(row, candidate.longHorizonPercentile)
        return row
      }),
  }))
}

/**
 * Why this player is worth having, in one line.
 *
 * Names the single strongest thing about them rather than listing every
 * figure, because the figures are already in the row beside it. A player
 * suggested for fixtures should read differently from one suggested for form,
 * which is the whole reason this sits next to the numbers rather than
 * replacing them.
 */
function describeBenefit(row: PickRow, longPercentile: number): string {
  const parts: string[] = []

  if (row.fixtureScore >= 7) {
    parts.push('one of the best fixture runs in the game right now')
  } else if (row.fixtureScore <= 5) {
    parts.push(
      'a hard run, so this is a bet on the player rather than the draw'
    )
  }

  if (row.form >= 6) {
    parts.push(`in form at ${row.form.toFixed(1)} over the last 30 days`)
  }

  if (longPercentile >= 0.95) {
    parts.push('among the very best of their position beyond this horizon')
  }

  if (row.netTransfers >= 100_000) {
    parts.push(
      `being bought by ${Math.round(row.netTransfers / 1000)}k managers this week`
    )
  } else if (row.netTransfers <= -100_000) {
    parts.push(
      `being sold by ${Math.round(Math.abs(row.netTransfers) / 1000)}k, so the market disagrees`
    )
  }

  if (row.ownership < 5) {
    parts.push('a differential at under 5% owned')
  }

  if (parts.length === 0) {
    return `Projects ${row.projected.toFixed(1)} points over the horizon.`
  }

  const sentence = parts.slice(0, 2).join(', and ')
  return sentence.charAt(0).toUpperCase() + sentence.slice(1) + '.'
}
